// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPUzt5snS-okzmJLl17xWMhI9qJjhkD6U',
    appId: '1:357744421352:web:aacaf8bd0a573a2b099c5d',
    messagingSenderId: '357744421352',
    projectId: 'auth3-4379d',
    authDomain: 'auth3-4379d.firebaseapp.com',
    storageBucket: 'auth3-4379d.appspot.com',
    measurementId: 'G-YH04MPLKCT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5i0bff-Hb3iXWDQQ7YyHI9JiHwLyhg-I',
    appId: '1:357744421352:android:e16680bf768b3d8d099c5d',
    messagingSenderId: '357744421352',
    projectId: 'auth3-4379d',
    storageBucket: 'auth3-4379d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-mRX0A77sBo_CGLfjKadqgcPvf6xllpg',
    appId: '1:357744421352:ios:7424b0248653cbca099c5d',
    messagingSenderId: '357744421352',
    projectId: 'auth3-4379d',
    storageBucket: 'auth3-4379d.appspot.com',
    androidClientId: '357744421352-2msl50dv3k7e0rtou5jqni671rp4ojnj.apps.googleusercontent.com',
    iosClientId: '357744421352-f51o5j2fl3tgp7mlthuaneuvgl17d74r.apps.googleusercontent.com',
    iosBundleId: 'com.example.auth3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-mRX0A77sBo_CGLfjKadqgcPvf6xllpg',
    appId: '1:357744421352:ios:7424b0248653cbca099c5d',
    messagingSenderId: '357744421352',
    projectId: 'auth3-4379d',
    storageBucket: 'auth3-4379d.appspot.com',
    androidClientId: '357744421352-2msl50dv3k7e0rtou5jqni671rp4ojnj.apps.googleusercontent.com',
    iosClientId: '357744421352-f51o5j2fl3tgp7mlthuaneuvgl17d74r.apps.googleusercontent.com',
    iosBundleId: 'com.example.auth3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPUzt5snS-okzmJLl17xWMhI9qJjhkD6U',
    appId: '1:357744421352:web:4f6421a6b587c1ef099c5d',
    messagingSenderId: '357744421352',
    projectId: 'auth3-4379d',
    authDomain: 'auth3-4379d.firebaseapp.com',
    storageBucket: 'auth3-4379d.appspot.com',
    measurementId: 'G-7DNPWNHEXH',
  );

}